lista = open("lista.txt", "a")
lista.writelines("oi\n")
lista.writelines("oi\n")
lista.writelines("oi\n")
lista.writelines("oi\n")
lista.writelines("oi\n")
lista.close()
lista = open("aaaaaa.txt", "a")
lista.writelines("eae\n")
lista.writelines("ear\n")
lista.writelines("eae\n")